set(CMAKE_SYSTEM_NAME Windows)
set(CMAKE_SYSTEM_PROCESSOR x86_64)
set(CMAKE_SYSTEM_VERSION 10.0)
set(CMAKE_C_COMPILER_TARGET x86_64-pc-windows-msvc)
set(CMAKE_CXX_COMPILER_TARGET x86_64-pc-windows-msvc)

set(XWIN_DIR "" CACHE PATH "xwin splat output holding crt/ and sdk/")
list(APPEND CMAKE_TRY_COMPILE_PLATFORM_VARIABLES XWIN_DIR)
if(NOT IS_DIRECTORY "${XWIN_DIR}/crt" OR NOT IS_DIRECTORY "${XWIN_DIR}/sdk")
    message(FATAL_ERROR "XWIN_DIR must point to an xwin splat output with crt/ and sdk/: '${XWIN_DIR}'")
endif()

find_program(CLANG_CL_EXECUTABLE clang-cl REQUIRED)
find_program(LLD_LINK_EXECUTABLE lld-link REQUIRED)
set(CMAKE_C_COMPILER "${CLANG_CL_EXECUTABLE}")
set(CMAKE_CXX_COMPILER "${CLANG_CL_EXECUTABLE}")
set(CMAKE_LINKER "${LLD_LINK_EXECUTABLE}")
set(CMAKE_C_COMPILER_WORKS 1)
set(CMAKE_CXX_COMPILER_WORKS 1)
set(CMAKE_C_ABI_COMPILED 1)
set(CMAKE_CXX_ABI_COMPILED 1)
set(CMAKE_C_COMPILER_ARCHITECTURE_ID x64 CACHE STRING "" FORCE)
set(CMAKE_CXX_COMPILER_ARCHITECTURE_ID x64 CACHE STRING "" FORCE)

set(CMAKE_SYSROOT "${XWIN_DIR}")
set(CMAKE_MSVC_RUNTIME_LIBRARY MultiThreadedDLL CACHE STRING "" FORCE)

execute_process(
    COMMAND "${CLANG_CL_EXECUTABLE}" /clang:-print-resource-dir
    OUTPUT_VARIABLE CLANG_RESOURCE_DIR
    OUTPUT_STRIP_TRAILING_WHITESPACE
)
set(XWIN_INCLUDE_FLAGS "/external:I${CLANG_RESOURCE_DIR}/include /external:I${XWIN_DIR}/crt/include /external:I${XWIN_DIR}/sdk/include/ucrt /external:I${XWIN_DIR}/sdk/include/shared /external:I${XWIN_DIR}/sdk/include/um /external:W0")
set(CMAKE_C_FLAGS_INIT "-vctoolsdir=${XWIN_DIR}/crt -winsdkdir=${XWIN_DIR}/sdk ${XWIN_INCLUDE_FLAGS}")
set(CMAKE_CXX_FLAGS_INIT "-vctoolsdir=${XWIN_DIR}/crt -winsdkdir=${XWIN_DIR}/sdk ${XWIN_INCLUDE_FLAGS} /EHsc")

set(XWIN_LINK_FLAGS "/LIBPATH:${XWIN_DIR}/crt/lib/x86_64 /LIBPATH:${XWIN_DIR}/sdk/lib/um/x86_64 /LIBPATH:${XWIN_DIR}/sdk/lib/ucrt/x86_64 /MANIFEST:NO")
set(CMAKE_EXE_LINKER_FLAGS_INIT "${XWIN_LINK_FLAGS}")
set(CMAKE_SHARED_LINKER_FLAGS_INIT "${XWIN_LINK_FLAGS}")
set(CMAKE_MODULE_LINKER_FLAGS_INIT "${XWIN_LINK_FLAGS}")

set(CMAKE_EXECUTABLE_SUFFIX .exe)
set(CMAKE_SHARED_LIBRARY_PREFIX "")
set(CMAKE_SHARED_LIBRARY_SUFFIX .dll)
set(CMAKE_IMPORT_LIBRARY_PREFIX "")
set(CMAKE_IMPORT_LIBRARY_SUFFIX .lib)
set(CMAKE_STATIC_LIBRARY_PREFIX "")
set(CMAKE_STATIC_LIBRARY_SUFFIX .lib)

set(CMAKE_FIND_ROOT_PATH "${XWIN_DIR}")
set(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
set(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
set(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)
